import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const prod = (process.argv[2] === "production");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this monorepo.
*/
`;

// Helper to copy files to Vault if available
function copyToVault() {
  const windowsVaultPath = "C:/Users/veloc/Documents/notes/Vault/.obsidian/plugins/obsidian-screenplay-mdsp";
  const wslVaultPath = "/mnt/c/Users/veloc/Documents/notes/Vault/.obsidian/plugins/obsidian-screenplay-mdsp";
  
  const isWSL = fs.existsSync("/mnt/c");
  const vaultPath = isWSL ? wslVaultPath : windowsVaultPath;

  try {
    if (fs.existsSync(path.dirname(vaultPath))) {
      if (!fs.existsSync(vaultPath)) {
        fs.mkdirSync(vaultPath, { recursive: true });
      }
      fs.copyFileSync("main.js", path.join(vaultPath, "main.js"));
      fs.copyFileSync("manifest.json", path.join(vaultPath, "manifest.json"));
      fs.copyFileSync("styles.css", path.join(vaultPath, "styles.css"));
      console.log(`Successfully deployed plugin files to Obsidian vault: ${vaultPath}`);
    } else {
      console.log(`Obsidian plugins folder not found at: ${path.dirname(vaultPath)}`);
    }
  } catch (e) {
    console.warn("Could not copy files to vault path:", e.message);
  }
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
  plugins: [{
    name: 'post-build',
    setup(build) {
      build.onEnd(result => {
        if (result.errors.length === 0) {
          copyToVault();
        }
      });
    },
  }],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
